name: Deploy GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4